<a href="https://colab.research.google.com/github/stepkapopka/DIP_using_MATLAB/blob/master/00_tensorflow_fundamentals_Duysekeev.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.15.0


1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
2. Find the shape, rank and size of the tensors you created.

In [ ]:
scalar = tf.constant(12)
scalar, scalar.ndim, scalar.shape, tf.size(scalar)

(<tf.Tensor: shape=(), dtype=int32, numpy=12>,
 0,
 TensorShape([]),
 <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [ ]:
vector = tf.constant([12, 5])
vector, vector.ndim, vector.shape, tf.size(vector)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([12,  5], dtype=int32)>,
 1,
 TensorShape([2]),
 <tf.Tensor: shape=(), dtype=int32, numpy=2>)

In [ ]:
matrix = tf.constant([[1, 12],
                      [12, 1]])
matrix, matrix.ndim, matrix.shape, tf.size(matrix)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 1, 12],
        [12,  1]], dtype=int32)>,
 2,
 TensorShape([2, 2]),
 <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [ ]:
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor, tensor.ndim, tensor.shape, tf.size(tensor)

(<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18]]], dtype=int32)>,
 3,
 TensorShape([3, 2, 3]),
 <tf.Tensor: shape=(), dtype=int32, numpy=18>)

3. Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [ ]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(5, 300))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(5, 300))

random_1, random_2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, ..., -1.071834  ,
         -1.0722276 , -0.00586287],
        [-0.88051033, -0.32426047, -2.4847078 , ...,  0.16512105,
          1.155565  , -0.10707551],
        [-1.5306779 , -0.86202925, -0.16359143, ...,  0.34288085,
          1.216793  , -1.24293   ],
        [ 0.84324265, -0.23379943,  0.4276398 , ..., -1.0428714 ,
         -0.73970354,  0.0177109 ],
        [ 0.04888754, -0.66408694, -1.787366  , ...,  0.1947453 ,
          0.5656089 ,  0.18439196]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, ..., -1.071834  ,
         -1.0722276 , -0.00586287],
        [-0.88051033, -0.32426047, -2.4847078 , ...,  0.16512105,
          1.155565  , -0.10707551],
        [-1.5306779 , -0.86202925, -0.16359143, ...,  0.34288085,
          1.216793  , -1.24293   ],
        [ 0.84324265, -0.23379943,  0.4276398 , ..., -1.0428714 

4. Multiply the two tensors you created in 3 using matrix multiplication.

In [ ]:
random_1 @ tf.transpose(random_2)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[272.44012  , -17.250706 , -34.88533  , -12.265072 , -22.346771 ],
       [-17.250706 , 335.51385  ,  -3.666809 ,  -1.7807384, -18.89357  ],
       [-34.88533  ,  -3.666809 , 333.2705   ,   4.595558 ,  -9.527701 ],
       [-12.265072 ,  -1.7807384,   4.595558 , 317.00775  ,   4.2550097],
       [-22.346771 , -18.89357  ,  -9.527701 ,   4.2550097, 295.76996  ]],
      dtype=float32)>

5. Multiply the two tensors you created in 3 using dot product.

In [ ]:
tf.tensordot(random_1, tf.transpose(random_2), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[272.44012  , -17.250706 , -34.88533  , -12.265072 , -22.346771 ],
       [-17.250706 , 335.51385  ,  -3.666809 ,  -1.7807384, -18.89357  ],
       [-34.88533  ,  -3.666809 , 333.2705   ,   4.595558 ,  -9.527701 ],
       [-12.265072 ,  -1.7807384,   4.595558 , 317.00775  ,   4.2550097],
       [-22.346771 , -18.89357  ,  -9.527701 ,   4.2550097, 295.76996  ]],
      dtype=float32)>

6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
7. Find the min and max values of the tensor you created in 6.

In [ ]:
random_3 = tf.random.Generator.from_seed(42)
random_3 = random_3.normal(shape=(224, 224, 3))
tf.reduce_max(random_3), tf.reduce_min(random_3)

(<tf.Tensor: shape=(), dtype=float32, numpy=4.4032865>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-4.848316>)

8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [ ]:
random_4 = tf.random.Generator.from_seed(42)
random_4 = random_4.normal(shape=(1, 224, 224, 3))
random_4_squeezed = tf.squeeze(random_4)
random_4_squeezed.shape, random_4_squeezed.ndim

(TensorShape([224, 224, 3]), 3)

9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [ ]:
import numpy as np
random_5 = tf.constant(np.random.randint(low=0, high=100, size=10))
random_5, tf.argmax(random_5)

(<tf.Tensor: shape=(10,), dtype=int64, numpy=array([67, 32, 15, 17, 33, 69, 53,  9, 84, 44])>,
 <tf.Tensor: shape=(), dtype=int64, numpy=8>)

10. One-hot encode the tensor you created in 9.

In [ ]:
tf.one_hot(random_5, depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>